version: "3"
services:
  mongo:
    image: mongo
    command: --enableFreeMonitoring on --serviceExecutor adaptive
    environment:
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_DB=timely"
    ports:
      - "27017:27017"
  redis:
    image: redis:4.0.11
    ports:
      - "6379:6379"
