version: "3"
services:
  postgres:
    image: postgres:10
    environment:
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_DB=timely"
    ports:
      - "5432:5432"
  redis:
    image: redis:4.0.11
    ports:
      - "6379:6379"
